---
- name: Sync files to build directory
  hosts: docker
  gather_facts: false
  remote_user: jenkins
  become: false
  tasks:
    - name: Ensure destination directory exists
      file:
        path: /home/jenkins/myproject/projects/
        state: directory
        mode: "0755"
        recurse: yes

    - name: Sync project files
      synchronize:
        src: "{{ playbook_dir }}/"
        dest: /home/jenkins/myproject/projects/

- name: Build and deploy Docker container
  hosts: ansible
  gather_facts: false
  remote_user: jenkins
  become: true
  tasks:
    - name: Manage container
      docker_container:
        name: nginx_container
        image: nginx_image:v1
        state: started
        ports:
          - "8183:80"
        recreate: yes
        build:
          path: /home/jenkins/myproject/projects/
