---
- hosts: docker
  gather_facts: false
  remote_user: jenkins
  become: true
  tasks:
    - name: Fetch files from Jenkins workspace to project dir
      synchronize:
        src: /home/jenkins/workspace/Myjob_github_ansible_docker/
        dest: /home/jenkins/myproject/projects/
        mode: pull

- hosts: ansible
  gather_facts: false
  remote_user: jenkins
  become: true
  tasks:
    - name: Stop old container (if exists)
      docker_container:
        name: nginx_container
        image: nginx_image:v1
        state: stopped

    - name: Remove old container
      docker_container:
        name: nginx_container
        image: nginx_image:v1
        state: absent

    - name: Remove old image
      docker_image:
        name: nginx_image:v1
        state: absent

    - name: Build new docker image
      docker_image:
        source: build
        name: nginx_image:v1
        build:
          path: /home/jenkins/myproject/projects/
        state: present

    - name: Run new container
      docker_container:
        name: nginx_container
        image: nginx_image:v1
        ports:
          - "8183:80"
        state: started

