---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:

    - name: Stop old container if running
      docker_container:
        name: nginx_container
        state: stopped
        force_kill: yes

    - name: Remove old container if exists
      docker_container:
        name: nginx_container
        state: absent

    - name: Remove old image if exists
      docker_image:
        name: mynginx:latest
        state: absent

    - name: Build new Docker image
      docker_image:
        name: mynginx:latest
        source: build
        build:
          path: /home/jenkins/ansible_docker_project

    - name: Run new container
      docker_container:
        name: nginx_container
        image: mynginx:latest
        ports:
          - "8183:80"
        state: started
